### ISSUE TITLE
Doesn't work in Safari Technology Preview

### ISSUE THREAD

**Issue by jorgegonzalez** [lautis/refined-github-safari#1]
First I want to say thank you so much for working on this and supporting Safari.

<img width="426" alt="screen shot 2018-06-25 at 1 43 38 pm" src="https://user-images.githubusercontent.com/12901172/41866329-d17514ec-787d-11e8-98e9-71492ad17eb2.png">

Not sure what changed in Safari 12 but it looks like this won't work anymore in Mojave.

**Comment by sberrevoets** [comment]
Safari has deprecated and removed old-style extensions. Safari App Extensions are the only way to make this available. I've been trying to make it work but the documentation is lackluster and it seems there are pretty strict rules about what can and cannot be done.

@lautis Is this something you're interested in investigating?

**Comment by lautis** [comment]
Yes, it’s interesting. At the same time, the changes required seem big as you noticed. For example, it’s not possible to inject HTML pages so that would need to be part of the native part. 

Apple has some documentation https://developer.apple.com/documentation/safariservices/safari_app_extensions/converting_a_legacy_safari_extension_to_a_safari_app_extension.

**Comment by sberrevoets** [comment]
I went down a number of paths, some more successful than others but always eventually got stuck. I'll continue looking at this, will post back once I have something working.

**Comment by pradyunsg** [comment]
@mathieudutour's fork seems to be working now.

**Comment by pradyunsg** [comment]
Okay, no. I spoke too early. :(

**Comment by lautis** [comment]
I'm not sure why the https://github.com/mathieudutour/refined-github isn't updated in extension gallery. The proper long-term solution of having an app extension hasn't been started in either repo :(
