### ISSUE TITLE
Missing "Filters" label on issues dropdown

### ISSUE THREAD

**Issue by gingerbeardman** [lautis/refined-github-safari#11]
With the extension:
![Screen shot 2020-01-07 at 16 05 36](https://user-images.githubusercontent.com/49612/71909313-afdb5180-3167-11ea-9e15-2d559cf195af.png)

Without:
![Screen shot 2020-01-07 at 16 05 50](https://user-images.githubusercontent.com/49612/71909316-b23dab80-3167-11ea-92da-ecbd7db673b0.png)

Thanks for this extension!

**Comment by lautis** [comment]
Thanks for reporting. The previous fix to Safari/Chrome incompatibilities didn't stand the test of time. Let's see if this one works more consistently.

<img width="688" alt="Screenshot 2020-01-12 at 12 17 20" src="https://user-images.githubusercontent.com/19264/72217385-88083700-3535-11ea-9703-b7d32c3f88f6.png">

**Comment by gingerbeardman** [comment]
I just realised I was using 2.0.19 

Does the extension not keep itself updated?

**Comment by lautis** [comment]
Unfortunately there are no automatic updates. I’d need to submit to app store for a good solution. 

Sparkle updates would be useless as at least I never run the app. I don’t know if the extension part of the bundle can trigger Sparkle for updates. If it can, this could be worth adding. 

The extension could download new JS from internet, but is a bit of a security issue and there complications when there are breaking changes with Safari interface. 

Installing using homebrew and periodically running brew cask upgrade refined-github-safari is the best option at the moment.

**Comment by gingerbeardman** [comment]
I'll do the brew method for now! Cheers
