### ISSUE TITLE
Cannot add review in v2.0.25

### ISSUE THREAD

**Issue by chdefrene** [lautis/refined-github-safari#12]
Hello, and thanks for this project! 

After upgrading to v2.0.25 I notice it no longer works when I try to add a review for pull requests. In my case, nothing happens when I press the "approve" button. 

This seems to have broken recently; I downgraded to v2.0.24 and now it works as expected again. I will gladly provide more details if needed 😊

![Skjermbilde 2020-01-17 kl  09 57 24](https://user-images.githubusercontent.com/6738930/72598330-e3f50600-390f-11ea-9a37-5239b222dfaa.png)

**Comment by chdefrene** [comment]
I see that this bug was introduced by refined-github, and seems to be taken care of: https://github.com/sindresorhus/refined-github/issues/2700

**Comment by lautis** [comment]
Thanks for reporting, I'll update the app tonight.

**Comment by lautis** [comment]
Should be fixed in 2.0.26!
