### ISSUE TITLE
Button height problem "Open all unread in tabs"

### ISSUE THREAD

**Issue by gingerbeardman** [lautis/refined-github-safari#14]
![Screen shot 2020-03-28 at 16 56 46](https://user-images.githubusercontent.com/49612/77831673-84de1980-7128-11ea-8d00-a89fb97217f2.png)

**Comment by lautis** [comment]
I can't reproduce with the latest version. Perhaps fixed in refined-github.

**Comment by gingerbeardman** [comment]
Yes indeed it has been, cheers!
