### ISSUE TITLE
Wrong avatar next to reactions

### ISSUE THREAD

**Issue by gingerbeardman** [lautis/refined-github-safari#15]
The red-outlined avatar should be mine?

![Screen shot 2020-05-22 at 11 17 37](https://user-images.githubusercontent.com/49612/82658470-edc0aa00-9c1e-11ea-8969-0811ba43f8a6.png)

ps: I do not see these avatars at all in official Chrome refined-github.

**Comment by lautis** [comment]
The issue seems to have been in the original extension: https://github.com/sindresorhus/refined-github/issues/3120

I'll release a new version with the fix.

**Comment by lautis** [comment]
2.0.35 doesn't show broken avatars. If the feature is reimplemented in refined-github, it should start also working in the safari version.
