### ISSUE TITLE
Clone or Download > Open in Desktop, button is gone

### ISSUE THREAD

**Issue by gingerbeardman** [lautis/refined-github-safari#16]
- "Open in Desktop" button is gone

> ![Screen shot 2020-06-21 at 22 59 31](https://user-images.githubusercontent.com/49612/85236130-eefa1800-b412-11ea-9147-dbbf53c69b37.png)

- reappears when i disable the extension

> ![Screen shot 2020-06-21 at 22 59 19](https://user-images.githubusercontent.com/49612/85236132-f1f50880-b412-11ea-8cf9-4ee2ee769812.png)

- chrome version does not have this problem

> ![Screen shot 2020-06-21 at 23 01 11](https://user-images.githubusercontent.com/49612/85236156-1cdf5c80-b413-11ea-8520-64d170f69139.png)

**Comment by gingerbeardman** [comment]
Also still gone with new GitHub repo design.

**Comment by lautis** [comment]
https://github.com/sindresorhus/refined-github/pull/3211 added rule to hide elements with class `js-remove-unless-platform. This rule does not apply on Chrome for the clone dialog, but on Safari and Firefox it applies. I'm not sure why. As this is also a Firefox bug, I'd hope that this could be addressed in refined-github.

**Comment by lautis** [comment]
Just when I was taking screenshots, GitHub deployed a change and now the Open in Desktop is also gone on Chrome if you have refined-github installed.

**Comment by lautis** [comment]
Fixed in 2.0.43.
