### ISSUE TITLE
Configurable personal token for GitHub API access

### ISSUE THREAD

**Issue by lautis** [lautis/refined-github-safari#4]
As noticed in #3, some features do not work as they required API token for GraphQL. 

Add a configuration option somewhere (in the .app?) to allow setting the personal API token.

**Comment by sberrevoets** [comment]
Given #7, what do you think is the best method to store the token? UserDefaults is an option, but isn't secure. Keychain is another option but isn't nearly as straightforward.

**Comment by lautis** [comment]
Refined GitHub only uses the sync storage for options, so we could assume a schema and treat the sync storage differently. My concern with #7 is mainly to avoid extra calls to potentially expensive GitHub API endpoints.

I'd prefer Keychain, but UserDefaults should work too. It shouldn't be any less secure than command-line apps like hub storing OAuth tokens in plain text files.

**Comment by nesl247** [comment]
Any update on this?

**Comment by lautis** [comment]
Implemented in #17.
