### ISSUE TITLE
Missing GitHub Enterprise Support

### ISSUE THREAD

**Issue by bsrz** [lautis/refined-github-safari#8]
Would it be possible to add GitHub Enterprise support?
Maybe a field in the options view to add one or more URLs?

**Comment by lautis** [comment]
In Safari extensions this is quite annoying. To my understanding, list of allowed domains must be included in a static XML file that is part of the signed binary.


```xml
<key>SFSafariWebsiteAccess</key>
<dict>
  <key>Allowed Domains</key>
  <array>
    <string>github.com</string>
    <string>gist.github.com</string>
  </array>
  <key>Include Secure Pages</key>
  <true/>
  <key>Level</key>
  <string>Some</string>
</dict>
```

It would be possible to include a bootstrap script on *every* page, and then have a script that only checks whether the extension code should be loaded or not. This would slow down (very slightly) all page loads.

I'm not currently interested in building such functionality myself. It might be easier to add your GitHub Enterprise domain to https://github.com/lautis/refined-github-safari/blob/master/Refined%20GitHub%20Extension/Info.plist and make your own builds.

**Comment by bsrz** [comment]
@lautis this worked!
Thank you!

**Comment by wearhere** [comment]
Hey @lautis , is it easier to support this using the new Safari extensions?

**Comment by lautis** [comment]
I don't think it is any easier, but there might be something I'm missing. The app has not yet been ported to use the WebExtensions API available in Safari 14.

**Comment by lautis** [comment]
Web extensions make this easier as there Safari has a separate control to enable an extension for a specific domain. #21 contains WIP for this.
